# Example configuration for Rust Forward Proxy with Pluggable Architecture
# Copy this to config.yml and modify as needed

# Basic server settings
listen_addr: "127.0.0.1:8080"
log_level: "info"
request_timeout: 30
max_body_size: 1048576  # 1MB

# Proxy implementation configuration (NEW!)
proxy_implementation:
  implementation: "pingora"  # Options: "pingora", "hyper", "reqwest"
  max_connections: 1000
  connection_timeout_ms: 10000
  request_timeout_ms: 30000
  enable_http2: true
  enable_connection_pooling: true

# Upstream server configuration
upstream:
  url: "http://localhost:3000"
  connect_timeout: 5
  keep_alive_timeout: 60

# Redis configuration (optional)
redis:
  url: "redis://redis:6379"
  pool_size: 10
  connection_timeout: 5
  command_timeout: 10

# Logging configuration
logging:
  enable_file_logging: true

# TLS/HTTPS configuration
tls:
  enabled: true
  https_listen_addr: "127.0.0.1:8443"
  cert_path: "certs/proxy.crt"
  key_path: "certs/proxy.key"
  interception_enabled: true
  auto_generate_cert: true
  cert_organization: "Rust Forward Proxy"
  cert_common_name: "proxy.local"
  cert_validity_days: 365
  min_tls_version: "1.2"
  skip_upstream_cert_verify: false
  root_ca_cert_path: "ca-certs/securly_ca.crt"
  ca_cert_path: "ca-certs/rootCA.crt"
  ca_key_path: "ca-certs/rootCA.key"

# HTTP client configuration (for legacy hyper-based components)
http_client:
  max_idle_per_host: 50
  idle_timeout_secs: 90
  connect_timeout_secs: 10
  enable_http2: true
  http2_stream_window_size: 2097152     # 2MB
  http2_connection_window_size: 8388608 # 8MB
  http2_keepalive_interval_secs: 30
  http2_keepalive_timeout_secs: 10
  http2_max_concurrent_streams: 100
  tcp_keepalive: true
  tcp_keepalive_interval_secs: 30

# Streaming configuration
streaming:
  max_log_body_size: 1048576  # 1MB
  max_partial_log_size: 1024  # 1KB  
  enable_response_streaming: true
  enable_request_streaming: false

# Performance profiles (choose one):
#
# High Performance Profile (Production):
# proxy_implementation:
#   implementation: "pingora"
#   max_connections: 2000
#   connection_timeout_ms: 5000
#   request_timeout_ms: 30000
#   enable_http2: true
#   enable_connection_pooling: true
#
# Development Profile:
# proxy_implementation:
#   implementation: "reqwest"
#   max_connections: 100
#   connection_timeout_ms: 15000
#   request_timeout_ms: 60000
#   enable_http2: false
#   enable_connection_pooling: false
#
# Balanced Profile:
# proxy_implementation:
#   implementation: "hyper"
#   max_connections: 500
#   connection_timeout_ms: 10000
#   request_timeout_ms: 30000
#   enable_http2: true
#   enable_connection_pooling: true
